"""CI must never publish the identity automatically generated by an SBF build."""

from fnmatch import fnmatch
from pathlib import Path


def test_sbf_ci_upload_cannot_include_generated_or_private_keypairs():
    source = Path(".github/workflows/verify.yml").read_text()
    upload = source.split("name: escrow-verification\n", 1)[1]
    paths = [line.strip() for line in upload.split("path: |\n", 1)[1].splitlines()]
    assert any(fnmatch("ci-evidence/sbf/gradientmine_escrow.so", pattern) for pattern in paths)
    for secret in (
        "ci-evidence/sbf/gradientmine_escrow-keypair.json",
        "ci-evidence/sbf/creator.json",
        "ci-evidence/validator.json",
        "ci-evidence/private/worker.json",
    ):
        assert not any(fnmatch(secret, pattern) for pattern in paths), secret
